<?php
declare(strict_types=1);
require_once __DIR__ . '/includes/bootstrap.php';
try {
    $pdo=connectDatabase();
    $user=requireCustomer($pdo);
    $today=date('Y-m-d');$now=date('H:i:s');
    $appointmentStmt=$pdo->prepare("SELECT a.*,m.name AS mechanic_name FROM appointments a INNER JOIN mechanics m ON m.id=a.mechanic_id WHERE a.user_id=:user_id AND a.status='scheduled' AND (a.appointment_date>:future_date OR (a.appointment_date=:current_date AND (a.appointment_time IS NULL OR a.appointment_time>:current_time))) ORDER BY a.appointment_date,a.appointment_time LIMIT 1");
    $appointmentStmt->execute(['user_id'=>$user['id'],'future_date'=>$today,'current_date'=>$today,'current_time'=>$now]);
    $existingAppointment=$appointmentStmt->fetch()?:null;
} catch(Throwable $error) { error_log($error->getMessage()); exit('Database connection failed. Import the SQL file and check config/database.php.'); }
$flash=pullFlash();$old=is_array($flash['old'])?$flash['old']:[];$fieldErrors=is_array($flash['fieldErrors'])?$flash['fieldErrors']:[];$minimumAppointmentDate=date('Y-m-d',strtotime('+1 day'));$selectedDate=$old['appointment_date']??$minimumAppointmentDate;$selectedMechanicId=(int)($old['mechanic_id']??0);
$mechanics=getMechanicsWithAvailability($pdo,$selectedDate);$summary=getWorkshopSummary($mechanics);
function oldValue(array $old,string $key):string{return e((string)($old[$key]??''));}
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="description" content="Secure car workshop appointment booking."><title>Book Appointment | Midnight Bento Garage</title><link rel="icon" type="image/svg+xml" href="<?= e(appUrl('assets/images/logo.svg')) ?>"><link rel="stylesheet" href="<?= e(appUrl('assets/css/style.css?v=20260720-2')) ?>"><link rel="stylesheet" href="<?= e(appUrl('assets/css/auth.css')) ?>"></head>
<body><div class="page-glow page-glow-one" aria-hidden="true"></div><div class="page-glow page-glow-two" aria-hidden="true"></div>
<header class="site-header glass-card"><a class="brand" href="<?= e(appUrl('customer/dashboard.php')) ?>"><img src="<?= e(appUrl('assets/images/logo.svg')) ?>" alt="" width="48" height="48"><span><strong>MIDNIGHT</strong><small>BENTO GARAGE</small></span></a><button class="menu-toggle" id="menuToggle" type="button" aria-label="Open navigation" aria-expanded="false">☰</button><nav class="main-nav" id="mainNav"><a href="<?= e(appUrl('customer/dashboard.php')) ?>">My Account</a><a class="active" href="#booking">Book Appointment</a><a href="<?= e(appUrl('customer/dashboard.php#history')) ?>">History</a><a href="#mechanics">Mechanics</a></nav><form class="logout-form" action="<?= e(appUrl('logout.php')) ?>" method="post"><?= csrfField() ?><button class="btn btn-secondary header-cta" type="submit">Logout</button></form></header>
<main class="page-shell">
<?php if($flash['message']!==''): ?><div class="toast toast-<?= e($flash['type']) ?>" role="status"><span class="toast-icon"><?= $flash['type']==='success'?'✓':($flash['type']==='warning'?'!':'×') ?></span><div><strong><?= $flash['type']==='success'?'Success':($flash['type']==='warning'?'Please note':'Could not continue') ?></strong><p><?= e($flash['message']) ?></p></div></div><?php endif; ?>
<section class="hero-grid" id="home"><article class="hero-card glass-card"><div class="hero-copy"><p class="eyebrow">SIGNED IN AS <?= e(strtoupper($user['full_name'])) ?></p><h1>Book Your Trusted <span class="highlight-text">Mechanic Online</span></h1><p class="hero-text">Customer ID: <strong><?= e($user['public_id']) ?></strong>. You can hold one upcoming appointment at a time.</p><a class="btn btn-primary" href="#booking"><?= $existingAppointment?'View Booking Status':'Start Booking' ?></a></div><div class="hero-image-wrap"><img src="<?= e(appUrl('assets/images/hero-car.webp')) ?>" alt="White performance car inside a bright modern workshop"></div></article>
<aside class="capacity-card glass-card"><div class="section-heading compact-heading"><div><span class="section-icon">▥</span><h2>Workshop Capacity</h2></div><span id="capacityDate" class="date-chip"><?= e(date('d M Y',strtotime($selectedDate))) ?></span></div><div class="capacity-content"><div class="donut" id="capacityDonut" style="--booked-percent: <?= (int)$summary['booked_percent'] ?>"><div><strong id="capacityFreeMain"><?= (int)$summary['free'] ?></strong><span>Free Places</span></div></div><dl class="capacity-list"><div><dt><span class="legend-dot success"></span>Available</dt><dd id="summaryFree"><?= (int)$summary['free'] ?></dd></div><div><dt><span class="legend-dot warning"></span>Booked</dt><dd id="summaryBooked"><?= (int)$summary['booked'] ?></dd></div><div><dt><span class="legend-dot danger"></span>Full Mechanics</dt><dd id="summaryFull"><?= (int)$summary['full'] ?></dd></div></dl></div><div class="system-status"><span>✓</span> Capacity is checked again securely on the server.</div></aside></section>
<section class="booking-layout" id="booking">
<article class="booking-form-card glass-card"><div class="section-heading"><div><span class="section-icon">▣</span><p class="section-kicker">Customer-linked booking</p><h2><?= $existingAppointment?'Appointment Already Booked':'Book an Appointment' ?></h2></div><span class="required-note">Customer access</span></div>
<?php if($existingAppointment): ?><div class="existing-booking-card"><span>✓</span><h3>You already have an upcoming appointment.</h3><p><?= e($existingAppointment['mechanic_name']) ?> · <?= e(date('d M Y',strtotime($existingAppointment['appointment_date']))) ?></p><a class="btn btn-primary" href="<?= e(appUrl('customer/dashboard.php')) ?>">View My Appointment</a></div>
<?php else: ?><form id="bookingForm" action="<?= e(appUrl('book_appointment.php')) ?>" method="post" novalidate><?= csrfField() ?><div class="form-grid"><div class="form-group"><label for="clientName">Full Name</label><input class="form-control readonly-control" id="clientName" name="client_name" value="<?= e($user['full_name']) ?>" readonly></div><div class="form-group"><label for="phone">Phone Number</label><input class="form-control readonly-control" id="phone" name="phone" value="<?= e($user['phone']) ?>" readonly></div><div class="form-group form-group-wide"><label for="address">Address</label><textarea class="form-control <?= isset($fieldErrors['address'])?'is-invalid':'' ?>" id="address" name="address" rows="3" maxlength="255" required><?= oldValue($old,'address') ?></textarea><small class="field-error" data-error-for="address"><?= e($fieldErrors['address']??'') ?></small></div><div class="form-group"><label for="carLicense">Car Registration Number</label><input class="form-control <?= isset($fieldErrors['car_license'])?'is-invalid':'' ?>" id="carLicense" name="car_license" value="<?= oldValue($old,'car_license') ?>" maxlength="50" required><small class="field-error" data-error-for="car_license"><?= e($fieldErrors['car_license']??'') ?></small></div><div class="form-group"><label for="carEngine">Car Engine Number</label><input class="form-control <?= isset($fieldErrors['car_engine'])?'is-invalid':'' ?>" id="carEngine" name="car_engine" value="<?= oldValue($old,'car_engine') ?>" maxlength="50" required><small class="field-error" data-error-for="car_engine"><?= e($fieldErrors['car_engine']??'') ?></small></div><div class="form-group form-group-wide"><label for="appointmentDate">Appointment Date</label><input class="form-control <?= isset($fieldErrors['appointment_date'])?'is-invalid':'' ?>" id="appointmentDate" name="appointment_date" type="date" min="<?= e($minimumAppointmentDate) ?>" value="<?= e($selectedDate) ?>" required><small>Requests must be made at least one day in advance. The admin will assign the time.</small><small class="field-error" data-error-for="appointment_date"><?= e($fieldErrors['appointment_date']??'') ?></small></div></div><input id="mechanicId" name="mechanic_id" type="hidden" value="<?= $selectedMechanicId?:'' ?>"><small class="field-error mechanic-field-error" data-error-for="mechanic_id"><?= e($fieldErrors['mechanic_id']??'') ?></small><button class="btn btn-primary btn-block" id="bookingButton" type="submit"><span class="button-label">Request Appointment</span><span class="button-loading" hidden>Requesting…</span></button></form><?php endif; ?></article>
<article class="mechanics-card glass-card" id="mechanics"><div class="section-heading"><div><span class="section-icon">◎</span><p class="section-kicker">Live availability</p><h2>Select Your Mechanic</h2></div><span class="date-chip" id="mechanicDateLabel"><?= e(date('d M Y',strtotime($selectedDate))) ?></span></div><p class="section-description">Each mechanic can accept a maximum of four appointments per day.</p><div class="mechanic-grid" id="mechanicGrid" aria-live="polite">
<?php foreach($mechanics as $mechanic): $selected=$selectedMechanicId===$mechanic['id']&&!$mechanic['is_full']; ?><button class="mechanic-card <?= e($mechanic['status']) ?> <?= $selected?'selected':'' ?>" type="button" data-mechanic-id="<?= (int)$mechanic['id'] ?>" data-mechanic-name="<?= e($mechanic['name']) ?>" <?= ($mechanic['is_full']||$existingAppointment)?'disabled':'' ?> aria-pressed="<?= $selected?'true':'false' ?>"><span class="selected-check">✓</span><span class="mechanic-avatar"><?= e(initials($mechanic['name'])) ?></span><strong><?= e($mechanic['name']) ?></strong><small><?= e($mechanic['role_title']) ?></small><span class="availability-text"><?= (int)$mechanic['free'] ?> of 4 places available</span><span class="slot-dots"><?php for($slot=1;$slot<=4;$slot++): ?><i class="<?= $slot<=$mechanic['booked']?'booked-dot':'free-dot' ?>"></i><?php endfor; ?></span><span class="mechanic-status"><?= $mechanic['is_full']?'Fully Booked':($mechanic['free']===1?'Almost Full':'Available') ?></span></button><?php endforeach; ?>
</div></article></section></main><footer class="site-footer"><img src="<?= e(appUrl('assets/images/logo.svg')) ?>" alt="" width="34" height="34"><p>Fast Booking. Trusted Mechanics. Protected Accounts.</p><a href="<?= e(appUrl('customer/dashboard.php')) ?>">My Account</a></footer><script src="<?= e(appUrl('assets/js/booking.js')) ?>"></script></body></html>
