<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/bootstrap.php';
try{$pdo=connectDatabase();$admin=requireAdmin($pdo);}catch(Throwable $error){error_log($error->getMessage());exit('Database connection failed.');}
$search=trim((string)($_GET['search']??''));$params=[];$where="WHERE a.status='completed'";
if($search!==''){$where.=' AND (u.public_id LIKE :search_public_id OR u.full_name LIKE :search_name OR u.phone LIKE :search_phone OR a.car_license LIKE :search_car OR m.name LIKE :search_mechanic)';$searchValue='%'.$search.'%';$params=['search_public_id'=>$searchValue,'search_name'=>$searchValue,'search_phone'=>$searchValue,'search_car'=>$searchValue,'search_mechanic'=>$searchValue];}
$sql="SELECT a.*,u.public_id,u.full_name AS customer_name,u.phone AS customer_phone,m.name AS mechanic_name FROM appointments a INNER JOIN users u ON u.id=a.user_id INNER JOIN mechanics m ON m.id=a.mechanic_id {$where} ORDER BY a.completed_at DESC,a.appointment_date DESC";$stmt=$pdo->prepare($sql);$stmt->execute($params);$appointments=$stmt->fetchAll();
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Appointment History | Midnight Bento Garage</title><link rel="icon" type="image/svg+xml" href="<?= e(appUrl('assets/images/logo.svg')) ?>"><link rel="stylesheet" href="<?= e(appUrl('assets/css/style.css')) ?>"><link rel="stylesheet" href="<?= e(appUrl('assets/css/admin.css?v=20260720-6')) ?>"><link rel="stylesheet" href="<?= e(appUrl('assets/css/auth.css')) ?>"></head><body class="admin-body history-page"><button class="admin-menu-toggle" id="adminMenuToggle" type="button" aria-label="Open admin menu" aria-expanded="false">☰</button>
<aside class="admin-sidebar" id="adminSidebar"><a class="brand admin-brand" href="<?= e(appUrl('admin/index.php')) ?>"><img src="<?= e(appUrl('assets/images/logo.svg')) ?>" alt="" width="52" height="52"><span><strong>MIDNIGHT</strong><small>BENTO GARAGE</small></span></a><nav class="admin-nav"><a href="<?= e(appUrl('admin/index.php')) ?>"><span>⌂</span>Dashboard</a><a href="<?= e(appUrl('admin/index.php#appointments')) ?>"><span>▣</span>Appointments</a><a class="active" href="<?= e(appUrl('admin/history.php')) ?>"><span>↻</span>History</a><a href="<?= e(appUrl('admin/index.php#capacity')) ?>"><span>◎</span>Mechanics</a><a href="<?= e(appUrl('admin/add_mechanic.php')) ?>"><span>+</span>Add Mechanic</a><a href="<?= e(appUrl('admin/create_admin.php')) ?>"><span>+</span>Create Admin</a><a href="<?= e(appUrl('account/change_password.php')) ?>"><span>⚿</span>Password</a></nav><div class="admin-role-card"><small>Signed in administrator</small><strong><?= e($admin['full_name']) ?></strong><span><?= e($admin['public_id']) ?></span><b>Administrator</b></div><form class="sidebar-logout" action="<?= e(appUrl('logout.php')) ?>" method="post"><?= csrfField() ?><button class="btn btn-secondary btn-block" type="submit">Logout</button></form></aside>
<main class="admin-main history-main"><header class="admin-topbar history-topbar"><div><p class="section-kicker">Completed customer work</p><h1>Appointment History</h1><p>Review completed workshop visits and quickly find any past appointment.</p></div><a class="btn btn-secondary" href="<?= e(appUrl('admin/index.php')) ?>">← Dashboard</a></header>
<section class="history-overview glass-card"><div class="history-overview-icon">↻</div><div><small>Completed appointments</small><strong><?= count($appointments) ?></strong><span><?= $search!==''?'Matching your search':'Available in history' ?></span></div><form class="history-search-form" method="get"><label for="historySearch">Find a completed appointment</label><div><input id="historySearch" name="search" type="search" value="<?= e($search) ?>" placeholder="Customer, phone, car or mechanic"><button class="btn btn-primary" type="submit">Search</button></div></form><?php if($search!==''): ?><a class="history-clear" href="<?= e(appUrl('admin/history.php')) ?>">Clear search</a><?php endif; ?></section>
<article class="history-table-card strong-card"><div class="table-heading"><div><p class="section-kicker">Completed only</p><h2>History Records</h2></div><span><?= count($appointments) ?> result<?= count($appointments)===1?'':'s' ?></span></div><div class="table-scroll"><table class="secure-admin-table"><thead><tr><th>Customer</th><th>Contact</th><th>Vehicle</th><th>Appointment</th><th>Mechanic</th><th>Completed</th></tr></thead><tbody><?php foreach($appointments as $a): ?><tr><td><strong><?= e($a['customer_name']) ?></strong><small class="table-subtext"><?= e($a['public_id']) ?></small></td><td><?= e($a['customer_phone']) ?></td><td><strong><?= e($a['car_license']) ?></strong><small class="table-subtext"><?= e($a['car_engine']) ?></small></td><td><strong><?= e(date('d M Y',strtotime($a['appointment_date']))) ?></strong><small class="table-subtext"><?= $a['appointment_time']!==null?e(date('h:i A',strtotime($a['appointment_time']))):'Time not assigned' ?></small></td><td><span class="mechanic-name-cell"><i><?= e(initials($a['mechanic_name'])) ?></i><?= e($a['mechanic_name']) ?></span></td><td><span class="completed-stamp">✓ <?= $a['completed_at']!==null?e(date('d M Y',strtotime($a['completed_at']))):'Completed' ?></span></td></tr><?php endforeach; ?><?php if(!$appointments): ?><tr><td class="empty-table" colspan="6"><strong>No completed appointments found.</strong><small>Completed appointments will appear here.</small></td></tr><?php endif; ?></tbody></table></div></article></main><script src="<?= e(appUrl('assets/js/admin.js')) ?>"></script></body></html>
