<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/bootstrap.php';
if ($_SERVER['REQUEST_METHOD']!=='POST') redirect(appUrl('admin/index.php'));
verifyCsrfOrFail();
try{$pdo=connectDatabase();$admin=requireAdmin($pdo);}catch(Throwable $error){error_log($error->getMessage());exit('Database connection failed.');}
$id=filter_var($_POST['appointment_id']??null,FILTER_VALIDATE_INT)?:0;$mechanicId=filter_var($_POST['mechanic_id']??null,FILTER_VALIDATE_INT)?:0;$date=trim((string)($_POST['appointment_date']??''));$time=trim((string)($_POST['appointment_time']??''));
if($id<1||$mechanicId<1||!validDate($date)||$date<date('Y-m-d')||!preg_match('/^(?:[01]\d|2[0-3]):[0-5]\d$/',$time)){setFlash('error','Select a valid date, time and mechanic.');redirect(appUrl('admin/index.php?edit='.$id));}
try{$pdo->beginTransaction();$appointment=$pdo->prepare('SELECT * FROM appointments WHERE id=:id FOR UPDATE');$appointment->execute(['id'=>$id]);$row=$appointment->fetch();if(!$row){$pdo->rollBack();setFlash('error','Appointment not found.');redirect(appUrl('admin/index.php'));}if($row['status']==='completed'){$pdo->rollBack();setFlash('warning','Completed appointments cannot be edited.');redirect(appUrl('admin/index.php'));}$mechanic=$pdo->prepare('SELECT id,name FROM mechanics WHERE id=:id AND is_active=1 FOR UPDATE');$mechanic->execute(['id'=>$mechanicId]);$m=$mechanic->fetch();if(!$m){$pdo->rollBack();setFlash('error','Mechanic not available.');redirect(appUrl('admin/index.php?edit='.$id));}$count=$pdo->prepare("SELECT COUNT(*) FROM appointments WHERE mechanic_id=:mechanic_id AND appointment_date=:date AND status='scheduled' AND id<>:id");$count->execute(['mechanic_id'=>$mechanicId,'date'=>$date,'id'=>$id]);if((int)$count->fetchColumn()>=DAILY_MECHANIC_LIMIT){$pdo->rollBack();setFlash('error','The selected mechanic is fully booked on that date.');redirect(appUrl('admin/index.php?edit='.$id));}$update=$pdo->prepare('UPDATE appointments SET appointment_date=:date,appointment_time=:time,mechanic_id=:mechanic_id WHERE id=:id');$update->execute(['date'=>$date,'time'=>$time,'mechanic_id'=>$mechanicId,'id'=>$id]);logAudit($pdo,(int)$admin['id'],'appointment_updated','appointment',$id,['old_date'=>$row['appointment_date'],'new_date'=>$date,'old_time'=>$row['appointment_time'],'new_time'=>$time,'old_mechanic_id'=>$row['mechanic_id'],'new_mechanic_id'=>$mechanicId]);$pdo->commit();setFlash('success','Appointment date and time updated successfully.');redirect(appUrl('admin/index.php'));}catch(Throwable $error){if($pdo->inTransaction())$pdo->rollBack();error_log($error->getMessage());setFlash('error','Something went wrong while updating the appointment.');redirect(appUrl('admin/index.php?edit='.$id));}
