<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/bootstrap.php';
try {
    $pdo=connectDatabase();$user=requireCustomer($pdo);$today=date('Y-m-d');$now=date('H:i:s');
    $active=$pdo->prepare("SELECT a.*,m.name AS mechanic_name,m.role_title FROM appointments a INNER JOIN mechanics m ON m.id=a.mechanic_id WHERE a.user_id=:user_id AND a.status='scheduled' AND (a.appointment_date>:future_date OR (a.appointment_date=:current_date AND (a.appointment_time IS NULL OR a.appointment_time>:current_time))) ORDER BY a.appointment_date,a.appointment_time LIMIT 1");
    $active->execute(['user_id'=>$user['id'],'future_date'=>$today,'current_date'=>$today,'current_time'=>$now]);$appointment=$active->fetch()?:null;
    $history=$pdo->prepare("SELECT a.*,m.name AS mechanic_name FROM appointments a INNER JOIN mechanics m ON m.id=a.mechanic_id WHERE a.user_id=:user_id AND (a.status='completed' OR a.appointment_date<:past_date OR (a.appointment_date=:current_date AND a.appointment_time IS NOT NULL AND a.appointment_time<=:current_time)) ORDER BY a.appointment_date DESC,a.appointment_time DESC");
    $history->execute(['user_id'=>$user['id'],'past_date'=>$today,'current_date'=>$today,'current_time'=>$now]);$historyAppointments=$history->fetchAll();
} catch(Throwable $error){error_log($error->getMessage());exit('Database connection failed.');}
$flash=pullFlash();
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Customer Dashboard | Midnight Bento Garage</title><link rel="icon" type="image/svg+xml" href="<?= e(appUrl('assets/images/logo.svg')) ?>"><link rel="stylesheet" href="<?= e(appUrl('assets/css/style.css')) ?>"><link rel="stylesheet" href="<?= e(appUrl('assets/css/auth.css')) ?>"></head>
<body><header class="site-header glass-card account-header"><a class="brand" href="<?= e(appUrl('customer/dashboard.php')) ?>"><img src="<?= e(appUrl('assets/images/logo.svg')) ?>" alt="" width="48" height="48"><span><strong>MIDNIGHT</strong><small>BENTO GARAGE</small></span></a><nav class="account-nav"><a class="active" href="<?= e(appUrl('customer/dashboard.php')) ?>">My Account</a><a href="<?= e(appUrl('index.php')) ?>">Book Appointment</a><a href="#history">History</a><a href="<?= e(appUrl('account/change_password.php')) ?>">Change Password</a></nav><form class="logout-form" action="<?= e(appUrl('logout.php')) ?>" method="post"><?= csrfField() ?><button class="btn btn-secondary" type="submit">Logout</button></form></header>
<main class="dashboard-shell"><?php if($flash['message']!==''): ?><div class="auth-message <?= e($flash['type']) ?>"><?= e($flash['message']) ?></div><?php endif; ?>
<section class="profile-hero glass-card"><div><p class="section-kicker">Customer profile</p><h1><?= e($user['full_name']) ?></h1><p>Your unique Customer ID connects your account and appointment.</p></div><div class="customer-id-card"><small>Customer ID</small><strong><?= e($user['public_id']) ?></strong><span>Customer account</span></div></section>
<section class="dashboard-grid"><article class="account-details strong-card"><div class="section-heading"><div><span class="section-icon">◎</span><p class="section-kicker">Identity</p><h2>Account Information</h2></div></div><dl class="details-list"><div><dt>Customer Name</dt><dd><?= e($user['full_name']) ?></dd></div><div><dt>Username</dt><dd><?= e($user['username']) ?></dd></div><div><dt>Phone</dt><dd><?= e($user['phone']) ?></dd></div><div><dt>Role</dt><dd><span class="role-badge customer">Customer</span></dd></div></dl></article>
<article class="appointment-summary strong-card"><div class="section-heading"><div><span class="section-icon">▣</span><p class="section-kicker">Current booking</p><h2>My Appointment</h2></div></div><?php if($appointment): ?><dl class="details-list"><div><dt>Mechanic</dt><dd><?= e($appointment['mechanic_name']) ?></dd></div><div><dt>Date</dt><dd><?= e(date('d M Y',strtotime($appointment['appointment_date']))) ?></dd></div><div><dt>Time</dt><dd><?= $appointment['appointment_time']!==null?e(date('h:i A',strtotime($appointment['appointment_time']))):'Waiting for admin assignment' ?></dd></div><div><dt>Car Registration</dt><dd><?= e($appointment['car_license']) ?></dd></div><div><dt>Engine Number</dt><dd><?= e($appointment['car_engine']) ?></dd></div><div><dt>Address</dt><dd><?= e($appointment['address']) ?></dd></div></dl><p class="single-appointment-note">You can book another appointment after this appointment time has passed.</p><?php else: ?><div class="empty-appointment"><span>▣</span><h3>No upcoming appointment</h3><p>You can book your next appointment now.</p><a class="btn btn-primary" href="<?= e(appUrl('index.php#booking')) ?>">Book Appointment</a></div><?php endif; ?></article></section>
<section class="appointment-history strong-card" id="history"><div class="section-heading"><div><span class="section-icon">↻</span><p class="section-kicker">Completed appointments</p><h2>Appointment History</h2></div><span class="history-count"><?= count($historyAppointments) ?></span></div><?php if($historyAppointments): ?><label class="history-search" for="historySearch">Search history<input class="form-control" id="historySearch" type="search" placeholder="Date, mechanic, registration or engine number"></label><div class="history-list" id="historyList"><?php foreach($historyAppointments as $item): ?><article><div><strong><?= e(date('d M Y',strtotime($item['appointment_date']))) ?></strong><small><?= $item['appointment_time']!==null?e(date('h:i A',strtotime($item['appointment_time']))):'Time not assigned' ?></small></div><div><strong><?= e($item['mechanic_name']) ?></strong><small><?= e($item['car_license']) ?> · <?= e($item['car_engine']) ?></small></div><span>Completed</span></article><?php endforeach; ?></div><p class="history-empty" id="historyNoResults" hidden>No history records match your search.</p><?php else: ?><p class="history-empty">Past appointments will appear here after their scheduled time has passed.</p><?php endif; ?></section>
</main><script src="<?= e(appUrl('assets/js/history.js')) ?>"></script></body></html>
